### ISSUE TITLE
Sehr guter Code, aber bitte Tickets nicht als Issues angeben.

### ISSUE THREAD

**Issue by btc-minion** [pbeineke05/RoboWars#6]
Bitte ein Projekt anlegen, in welchem die Tickets verstaut werden. Beispiel: https://github.com/users/DanielB-btc/projects/1
und die Aufgaben nicht als Issue formulieren.

**Comment by pbeineke05** [comment]
Hey, ich hatte tatsächlich bereits ein Projekt erstellt. Dieses war allerdings nicht public... Dies habe ich jetzt angepasst, siehe hier https://github.com/users/pbeineke05/projects/1/views/1

> Bitte ein Projekt anlegen, in welchem die Tickets verstaut werden. Beispiel: https://github.com/users/DanielB-btc/projects/1 und die Aufgaben nicht als Issue formulieren.

**Comment by btc-minion** [comment]
Perfekt, sehr gute Arbeit
